### ISSUE TITLE
When will the codes be released 

### ISSUE THREAD

**Issue by DongChen06** [PQ3D/PQ3D#1]
Thanks for the great work, when do you approximate the codes will be released?

**Comment by zhuziyu-edward** [comment]
As our paper PQ3D is still under review, we plan to release the code after the final decision is made. Please stay tuned!

**Comment by zhuziyu-edward** [comment]
@yahooo-m Thank you for your interest in our work! We have been busy deploying our model to huggingface recently. The rest of the codes will be released in one or two weeks. You can try our huggingface demo here https://huggingface.co/spaces/li-qing/PQ3D-Demo.
