### ISSUE TITLE
How to execute tasks in custom datasets

### ISSUE THREAD

**Issue by yyy6812** [PQ3D/PQ3D#2]
Hi,

Thanks for your excellent work!

I want to ask about How can I implement these tasks in my own custom datasets.
And if possible, hope  you coulde release some inference codes, to help easily use your checkpoints to test the effect with Intuitive output rather than indicator analysis.

**Comment by zhuziyu-edward** [comment]
Thank you for your interest in our work. 

1. About fast inference, you can check out our huggingface-demo here https://huggingface.co/spaces/li-qing/PQ3D-Demo. This demo has graphic visualization and a very easy-to-use interface. 
2. For custom dataset, we are building a pipeline to upload RGB-D stream and automatically process data and set up model inference. We will update the repo after building it.

Best,
Ziyu
