### ISSUE TITLE
About the pretrained Pointnet++

### ISSUE THREAD

**Issue by OasisYang** [PQ3D/PQ3D#3]
Hi, 

Thanks for releasing your excellent work! I have some questions regarding to the training process. I noticed you employed a pre-trained PointNet++ as the point encoder in your work. I'm curious about two aspects:

1. Could you provide details on the pre-training process for PointNet++?
2. How does the result differ if it is trained from scratch?

Thanks for your insights!

**Comment by zhuziyu-edward** [comment]
Thank you for your interest in our work.
1. PointNet++ is from 3D-VisTA: Pre-trained transformer for 3D Vision and text alignment, https://github.com/3d-vista/3D-VisTA.
2. We do not conduct rigorous experiments on training it from scratch. Intuitively, like 2D vision language models, using a pre-trained backbone will generally lead to better performance.

**Comment by ayushjain1144** [comment]
Is the U-Net backbone trained from scratch?

**Comment by zhuziyu-edward** [comment]
@ayushjain1144 Yes
