### ISSUE TITLE
Difference among datasets

### ISSUE THREAD

**Issue by yyy6812** [PQ3D/PQ3D#5]
Dear authors,

Could you give some more detailed description for the `[scene_ver_aux]` and `[scene_verse_pred]`  data?

I wonder why we need to load the `[scene_verse_pred]`  data and what's the purpose of using the `[match_gt_to_pred]` function at the begining.

Thanks a lot!

**Comment by Yu-Zhou-Wang** [comment]
That's a good question. In addition, could you also explain how `[scene_verse_pred]` is produced? Are they the "unsupervised graph-based segmentation and masks" mentioned in the paper?

**Comment by zhuziyu-edward** [comment]
scene_verse_base stores data from sceneverse, which contains point clouds and instance annotations.
scene_verse_aux and scene_verse_pred stores other meta information, segment annotations, and features. 
The segment grouping is from https://github.com/ScanNet/ScanNet/tree/master/Segmentator.

**Comment by Yu-Zhou-Wang** [comment]
Hi thanks for answering the question. However, I'm still kind of confused on how data in `{scene_verse_pred}` is generated. Can you please comment on this?
