### ISSUE TITLE
Ask for performance on ScanQA val set

### ISSUE THREAD

**Issue by WeitaiKang** [PQ3D/PQ3D#7]
Dear authors,

Thanks for you great job! I wonder if you can release your performance on ScanQA val set, as lots of works follow that benchmark. I guess it will improve the impact of your paper when others want to cite your method and compare with you on that benchmark.

Look forward to your response!

**Comment by zhuziyu-edward** [comment]
Hi, the result on ScanQA val set is 22.1, EM@1.

**Comment by WeitaiKang** [comment]
Hi thanks for your response! Could you share the results of METEOR, ROUGE on ScanQA val which people commonly use to compare?
