### ISSUE TITLE
There are nan values in voxel obj feat pred.

### ISSUE THREAD

**Issue by strongwolf** [PQ3D/PQ3D#8]
Hi, all the values are nan for some obj voxel pred feat in some scenes including 0779_00, 0753_00, 0307_00.

**Comment by zhuziyu-edward** [comment]
Hi, do these values affect training and testing?  I find no error when running the code.

Best,
Ziyu

**Comment by strongwolf** [comment]
There will be an error when using 'pred' pc_type for training even though the default setting is 'gt' pc_type.
